Repository ClimateImpactLab/open-estimate, pull requests merged in 2020-09, with the labels that each got.

#52 Speed up numpy array sum
  openest/generate/daily.py
Labels: enhancement

#30 WIP: Merge Release-2.0 changes into master
  openest/curves/smart_linextrap.py
  openest/curves/ushape_numeric.py
  openest/generate/fast_dataset.py
  openest/generate/functions.py
  openest/generate/smart_curve.py
  openest/generate/yearly.py
  openest/models/curve.py
  openest/test/curves/allcalcs.csv
  openest/test/curves/polymins.csv
  openest/test/curves/test_ushape.py
  openest/test/curves/test_ushape_marginal.py
  requirements.txt
Labels: bug, enhancement

#62 Fix several small but troublesome issues in openest/generate/smart_curve.py
  openest/generate/smart_curve.py
Labels: bug
